services:
  nginx:
    image: nginx:latest
    container_name: dacs2024-nginx
    ports:
      - "80:80"
    volumes:
      #- ./web-app/browser:/usr/share/nginx/html/urbancheck:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web-app/browser/:/usr/share/nginx/html/urbancheck:ro
      - ./test/:/test:ro
    restart: unless-stopped
      #    command: /bin/bash -c "chmod -R 755 /web-app && nginx -g 'daemon off'"
    depends_on:
      - keycloak
    networks:
      - dacs2024_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: dacs2024-keycloak
    ports:
      - "8888:8080"
    restart: unless-stopped 
    command: ["start-dev"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    networks:
      - dacs2024_network

networks:
  dacs2024_network:
    driver: bridge

