services:
  nginx:
    image: nginx:latest
    container_name: dacs2024-nginx
    ports:
      - "80:80"
    volumes:
      #- ./web-app/browser:/usr/share/nginx/html/urbancheck:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./urbancheck-fe-build/:/usr/share/nginx/html/urbancheck
      - ./test/:/test:ro
    restart: unless-stopped
      #    command: /bin/bash -c "chmod -R 755 /web-app && nginx -g 'daemon off'"
    depends_on:
      - keycloak
    networks:
      - dacs2024_network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: dacs2024-keycloak
    ports:
      - "8888:8080"
    volumes:
      - ./urb-keycloak-theme/:/opt/keycloak/themes
      - ./realm-config-urbancheck.json:/opt/keycloak/data/import/realm-config-urbancheck.json
    restart: unless-stopped 
    command: ["start-dev", "--import-realm"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm-config-urbancheck.json
    networks:
      - dacs2024_network

networks:
  dacs2024_network:
    driver: bridge

